### ISSUE TITLE
WSGI Layers Development

### ISSUE THREAD

**Issue by uniphil** [Queens-Hacks/qcumber-api#6]
Hey @Graham42 -- I pulled your `skeleton-routed` branch to my `skeleton` branch and merged so that the tests passed again. I see you've created some qcumber-prefixed things in there, which I'm all for. I didn't merge any of that stuff though, so it's a bit redundant. 

.... or... I'm confused now. I don't really know what I did. I'm sick and in bed, (yeah gonna use that excuse since it's there)... Anyway I merged some stuff and maybe it's good or maybe bad... hey the tests pass! Where am I? Who am I?

**Comment by Graham42** [comment]
I think you actually included some stuff from the `bare-bones` branch which was before I had any idea what was going on, I deleted the folder and manage file from that. Also deleted the branch since it contained nothing of value

**Comment by uniphil** [comment]
Yeah afterward it made sense: I did `git checkout bare-bones` just to see what was up, and then `git checkout skeleton`, and then `git merge skeleton-routed`. The extra folder and stuff stuck around from when I'd checked out `bare-bones`, and I ended up committing it all in the merge. Oops.
